### ISSUE TITLE
Change of colors

### ISSUE THREAD

**Issue by Julian-Idl** [Hadi-koubeissi/Discord-bot-website-template#13]
Hi iam using your template for a discord bot website. I like it but the 1 thing i want to change is the color from blue to purple and I tried doing it by editing the bootstart.min.css but only few of the colors are changing like the invite button and login buttons others stay the same. Can you pls help me out on how to change it?

**Comment by hadi-4100** [comment]
Hello there!, dont change any think on `bootstrap.min.css`, if you want to change *Aris* word color you can change it on the html file

**Comment by hadi-4100** [comment]
![Screenshot_٢٠٢٢٠٨١٥-٢١٥٢٢٣_Chrome](https://user-images.githubusercontent.com/42873015/184698121-d35fa2b0-c2fb-4167-a166-98784ff103f9.jpg)

Another more extensive explanation. 
 In the picture everything is clear, the color is related to the word `text-info`, to change it you can go to this website: https://getbootstrap.com/docs/5.2/customize/color/

For example, you want the black color, its code is `dark`, you delete the word `info` and put dark, as follows `text-dark`

**Comment by Julian-Idl** [comment]
But the colour iam looking for does not have a code. For example i want the colour `$pink-800` but there is not code for it what should i do?

**Comment by hadi-4100** [comment]
You cannot put colors other than the ones in the bootstrap site, because the template is built on it, I don't know if there is another way in bootstrap that allows you to put the color you want, in this regard you must search for an answer to your question

**Comment by Julian-Idl** [comment]
okay than thanx of the reply :)

**Comment by hadi-4100** [comment]
Welcome, no problem
