### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NeeL-YT** [Hadi-koubeissi/Discord-bot-website-template#8]
![Screenshot_2022-02-12-06-17-38-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/75595584/153689084-7b70858e-bd3c-4a98-a469-b3284213d6e6.jpg)
This as you can see is offset in desktop mode chrome! Mobile
Many spaces are left in bottom

**Comment by Hadi-koubeissi** [comment]
The entire design will be changed soon

**Comment by NeeL-YT** [comment]
Soon like any eta??

**Comment by Hadi-koubeissi** [comment]
Soon...
